### ISSUE TITLE
remove clusters and implement env override instead

### ISSUE THREAD

**Issue by kamontat** [kc-workspace/go-lib#4]
## How env override works

override configuration base on `--env` user pass

for example
```yaml
test: true

_:
  production:
    test: false
```

When user call cli without `--env` **test** should be `true` 
however, if user pass --env production then **test** should be `false`
